AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'libs/**/*'
    - 'app/channels/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'path', 'get']