---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/books":
    get:
      summary: Get all books
      tags:
      - Book
      responses:
        '200':
          description: books found
    post:
      summary: Creates a book
      tags:
      - Book
      parameters: []
      responses:
        '200':
          description: book created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                genre:
                  type: string
                author:
                  type: string
                publication_at:
                  type: string
                publisher:
                  type: string
              required:
              - title
              - content
  "/api/v1/books/{id}":
    get:
      summary: Get a book by id Book
      tags:
      - Book
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: book found
        '404':
          description: book not found
servers:
- url: "{protocolHost}://{defaultHost}"
  variables:
    defaultHost:
      default: localhost:3000
    protocolHost:
      default: http
